twig:
    default_path: '%kernel.project_dir%/templates'
    #form_themes: ['tailwind_2_layout.html.twig']

    globals:
        app_version: '%app.version%'

when@test:
    twig:
        strict_variables: true
        #form_themes: ['tailwind_2_layout.html.twig']
