<?php

/**
 * Returns the importmap for this application.
 *
 * - "path" is a path inside the asset mapper system. Use the
 *     "debug:asset-map" command to see the full list of paths.
 *
 * - "entrypoint" (JavaScript only) set to true for any module that will
 *     be used as an "entrypoint" (and passed to the importmap() Twig function).
 *
 * The "importmap:require" command can be used to add new entries to this file.
 *
 * This file has been auto-generated by the importmap commands.
 */
return [
    'app' => [
        'path' => './assets/app.js',
        'entrypoint' => true,
    ],
    '@hotwired/stimulus' => [
        'version' => '3.2.2',
    ],
    '@symfony/stimulus-bundle' => [
        'path' => './vendor/symfony/stimulus-bundle/assets/dist/loader.js',
    ],
    'vue' => [
        'version' => '3.4.15',
        'package_specifier' => 'vue/dist/vue.esm-bundler.js',
    ],
    '@vue/runtime-dom' => [
        'version' => '3.4.15',
    ],
    '@vue/compiler-dom' => [
        'version' => '3.4.15',
    ],
    '@vue/shared' => [
        'version' => '3.4.15',
    ],
    '@vue/runtime-core' => [
        'version' => '3.4.15',
    ],
    '@vue/compiler-core' => [
        'version' => '3.4.15',
    ],
    '@vue/reactivity' => [
        'version' => '3.4.15',
    ],
    '@symfony/ux-vue' => [
        'path' => './vendor/symfony/ux-vue/assets/dist/loader.js',
    ],
    'bootstrap' => [
        'version' => '5.3.2',
    ],
    '@popperjs/core' => [
        'version' => '2.11.8',
    ],
    'bootstrap/dist/css/bootstrap.min.css' => [
        'version' => '5.3.2',
        'type' => 'css',
    ],
    'axios' => [
        'version' => '1.6.7',
    ],
    'lodash-es' => [
        'version' => '4.17.21',
    ],
    'marked' => [
        'version' => '12.0.0',
    ],
    'node-sass' => [
        'version' => '9.0.0',
    ],
    'vue-axios' => [
        'version' => '3.5.2',
    ],
    'vue-loader' => [
        'version' => '17.4.2',
    ],
];
