<?php
namespace App\Tests;

use App\Tests\Helper\Fixtures\FixturesTrait;
use Symfony\Bundle\FrameworkBundle\KernelBrowser;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\DependencyInjection\Container;

class AppWebTestCase extends WebTestCase
{
    use FixturesTrait;

    protected Container $container;

    protected KernelBrowser $client;

    public function setUp(): void
    {
        $this->client = static::createClient();
        $this->container = static::getContainer();
        $this->em = $this->container->get('doctrine')->getManager();

        $this->client->request('GET', '/');
        $session = $this->client->getRequest()->getSession();
        $session->set('_locale', 'fr');

        //parent::setUp(); // TODO: Change the autogenerated stub
    }

}