# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  app.supported_locales: 'fr|en|es'
  app.api_version: 'v1'
  app.ip_api_active_filter: true  #Si true alors filtre l'accès à l'API par les API défini dans app.ip_api_authorize
  app.ip_api_authorize: [127.0.0.1]
  app.default_locale: 'fr'
  app.default_database_prefix: '' # un "_" est ajouté par défaut, laissez vide si pas de prefix
  app.default_database_schema: '%env(NATHEO_SCHEMA)%'  # schéma de la base de donnée
  app.version: 'dev-11-2024'
  app.current_branche: 'master'
  # Permet d'activer le mode débug du CMS
  # En débug mode, créer un type d'utilisateur par droit dans les fixtures
  # En débug mode, créer un token par droits dans les fixtures
  app.debug_mode: true

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  App\EventListener\DatabaseTablePrefixListener:
    arguments:
      $prefix: '%app.default_database_prefix%'
      $schema: '%app.default_database_schema%'
    public: true
    tags:
      - { name: doctrine.event_subscriber }

  App\EventListener\ExceptionListener:
    tags: [ kernel.event_listener ]

  App\EventListener\OverwriteListener:
    tags:
      - { name: kernel.event_listener }
    arguments:
      $serviceLocator: !tagged_locator { tag: 'controller.service_arguments' }